### ISSUE TITLE
Only part of a ReadProcessMemory or WriteProcessMemory request was Completed

### ISSUE THREAD

**Issue by RJ4706** [sagefantasma/MGS2-Cheat-Trainer#26]
It seems like the Process being passed trying to determine the offset is bad.
![image](https://github.com/sagefantasma/MGS2-Cheat-Trainer/assets/7784071/531ddadb-2916-4cab-9454-91e8f1f4b980)

**Comment by RJ4706** [comment]
![image](https://github.com/sagefantasma/MGS2-Cheat-Trainer/assets/7784071/0b5e7226-8d5e-468f-b3a9-ed5ac04eaf2b)
I already submitted a pull request to which I believe will fix the issue but it should lead you to find the actual reason the MGS2Monitor isn't working correctly.

**Comment by sagefantasma** [comment]
This looks like a duplicate, so I'll just reference this in the other ticket (#27)
