### ISSUE TITLE
[Weapons] C4 page reads numeric values from claymore page

### ISSUE THREAD

**Issue by DuncanCasteleyn** [sagefantasma/MGS2-Cheat-Trainer#57]
![afbeelding](https://github.com/user-attachments/assets/7dcbb79a-d6ca-4434-8f0e-6da6d73015e7)
![afbeelding](https://github.com/user-attachments/assets/857b484a-19c9-44f8-b687-9db1809e705b)

**Comment by sagefantasma** [comment]
Good catch; I've identified the issue and will be deploying a fix today. Thanks!

**Comment by DuncanCasteleyn** [comment]
Thanks, looking forward to the next release.
