### ISSUE TITLE
Trainer crashes after 30 seconds when game is launched

### ISSUE THREAD

**Issue by RJ4706** [sagefantasma/MGS2-Cheat-Trainer#59]
For some reason, the code detects that the process has exited when in reality it hasn't. I'm assuming maybe it's a Windows issue not your code. Just wondering if you have seen anything like this before.
![Screenshot 2024-12-10 161142](https://github.com/user-attachments/assets/72f225c9-aa0e-4b33-a140-a505b46cc396)

**Comment by sagefantasma** [comment]
That's more than likely a windows 11 issue. If you run the trainer in admin mode, I believe that should clear the issue right up - this is something we've seen a few times before with the MGS1 and MGS3 trainers

**Comment by RJ4706** [comment]
So I can't right click and Run as Administrator on the Application reference. So I started command prompt in Administrator mode, changed directory to the application reference and started your application. The result is still the same, the trainer crashed. I can't even find any information inside Event Viewer either.

**Comment by sagefantasma** [comment]
To run the app as administrator: open up the trainer, go to 'Help' -> 'View Logs'. In the File Explorer window that opens, go up one level and you can then run `MGS2 MC Cheat Trainer.exe` as admin. That _should_ be all you need for getting it to run on Windows 11. 

I'll plan to have the next version auto-prompt for administrator on launch since Windows 10 is going out of service in less than a year, and this is a Windows 11 exclusive bug.

![image](https://github.com/user-attachments/assets/0910a34b-42ae-46ee-9313-e909b7fb207c)

**Comment by RJ4706** [comment]
Fresh logs, the game was already launched and I made sure the application started in Administrator mode. I could tell because the Cheats tab was the displayed at the start. This time, it didn't take 30 seconds it crashed within 10 seconds.

[MGS2MonitorDebuglog.log](https://github.com/user-attachments/files/18103523/MGS2MonitorDebuglog.log)
[ControllerDebuglog.log](https://github.com/user-attachments/files/18103524/ControllerDebuglog.log)
[MainDebuglog.log](https://github.com/user-attachments/files/18103525/MainDebuglog.log)
[MemoryManagerDebuglog.log](https://github.com/user-attachments/files/18103526/MemoryManagerDebuglog.log)

**Comment by RJ4706** [comment]
Fresh logs again, this time game was not started, just started the application. The game launched and a couple of seconds later, the trainer crashed.

[MGS2MonitorDebuglog.log](https://github.com/user-attachments/files/18103541/MGS2MonitorDebuglog.log)
[ControllerDebuglog.log](https://github.com/user-attachments/files/18103538/ControllerDebuglog.log)
[MemoryManagerDebuglog.log](https://github.com/user-attachments/files/18103540/MemoryManagerDebuglog.log)
[MainDebuglog.log](https://github.com/user-attachments/files/18103539/MainDebuglog.log)

**Comment by sagefantasma** [comment]
Are you getting an actual unhandled exception window that pops up? If not, can you check your TrainerConfig.json(in the 'Helpers' subfolder next to the 'logs' subfolder) as it might be automatically closing itself with the "Close Trainer with Game" option. I'm able to replicate the logs you're getting, but not the crashing behavior.

I don't have a Windows 11 machine, so if you _are_ getting crashes, it might be prudent to pull the latest version on main and try running it through Visual Studio to get some extra debugging info.

**Comment by RJ4706** [comment]
That seemed to do the trick. "closeTrainerWithGame":true was changed to "closeTrainerWithGame":false and the trainer doesn't crash.
