### ISSUE TITLE
Infinite Emma Health Crash

### ISSUE THREAD

**Issue by CarterWSlade** [sagefantasma/MGS2-Cheat-Trainer#61]
I think after I activate Emma Infinite Health to pass through sniping session, everytime Emma get 1 hit game crashes.

Is this happening just to me or anyone else is happening this crash as well?

**Comment by sagefantasma** [comment]
This cheat was designed specifically for the regular escort with Emma - not with the sniping session. It seems like the damage Emma takes during twilight sniping is programmed differently from standard bullet/explosive damage; so that crashing behavior would happen to everyone.

**Comment by CarterWSlade** [comment]
Oh, I thought sniping sessions were included. 
Thanks for the comment anyway
