### ISSUE TITLE
Player Health Modification

### ISSUE THREAD

**Issue by sagefantasma** [sagefantasma/MGS2-Cheat-Trainer#9]

**Comment by tsushka** [comment]
hello! I can say this is my first time using mods, so I didn't really understand if it was a program error or if I did something wrong. I want to make my HP immutable, but I don't know what to write in the Life Bar to apply the changes in the game. If I write something and press "Set", the program shows "Failed to update game string". Can you please help me what do I need to do? Could there be a problem in the steam version of the game?
(sorry for possible mistakes, I don't speak english haha)

**Comment by sagefantasma** [comment]
@tsushka There could be several different things going on, I just have to ask a few questions to help narrow down what might be happening:

1) Are you using a Windows computer?
2) Do any of the Item or Weapon functions work?
3) Are you trying to do this with the game already open?
4) Are you using the mod to launch MGS2?

If your answer to all of these questions is "yes", then it would be very helpful if you could go to the "Help" menu and select the "View Logs" option that appears. That should open a File Explorer window with several different log files in it; please take those files and upload them here so I can take a look and try and figure out what's going on :)

![image](https://github.com/sagefantasma/MGS2-Cheat-Trainer/assets/8712389/63c1d2af-959b-4b9e-9d17-2d445077ed7c)
![image](https://github.com/sagefantasma/MGS2-Cheat-Trainer/assets/8712389/24f31c54-9640-4e75-959b-b5d1dc8cca45)

I uploaded these two images to try and help you find the logs more easily :)

**Comment by tsushka** [comment]
[MemoryManagerDebuglog.log](https://github.com/sagefantasma/MGS2-Cheat-Trainer/files/14466069/MemoryManagerDebuglog.log)
[MGS2MonitorDebuglog.log](https://github.com/sagefantasma/MGS2-Cheat-Trainer/files/14466070/MGS2MonitorDebuglog.log)
[ControllerDebuglog.log](https://github.com/sagefantasma/MGS2-Cheat-Trainer/files/14466071/ControllerDebuglog.log)
[MainDebuglog.log](https://github.com/sagefantasma/MGS2-Cheat-Trainer/files/14466072/MainDebuglog.log)

**Comment by tsushka** [comment]
![Screenshot_4](https://github.com/sagefantasma/MGS2-Cheat-Trainer/assets/161836697/e3fa2de8-5483-4474-b352-58f7179b2d25)
About the second one, I tried with a box, for example, and that's what happened

**Comment by sagefantasma** [comment]
@tsushka it looks like the trainer isn't recognizing MGS2 as currently running - are you starting the game through Steam? Right now there is a software limitation that requires you to launch the game through the Cheat Trainer. Launching through Steam will not work. I have plans to fix this limitation in the future, but for now you must use the mod to launch MGS2 in order for the mod to work. Let me know if this does not fix your issue.

**Comment by tsushka** [comment]
@sagefantasma Yes, I log into the game using the trainer, but the same problem with applying the changes still remains...

**Comment by sagefantasma** [comment]
@tsushka the errors you are getting are indicative that MGS2 either **is not currently running**, or that it _is not being started by the trainer_. With this version of the Cheat Trainer, you _must start MGS2_ with either the Options menu or through the auto-start feature offered by the Cheat Trainer. The logs you provided show that the trainer has not yet launched MGS2 successfully. You appear to have at least tried to set a launch path for MGS2, but it isn't valid and the trainer is unable to launch MGS2.
![image](https://github.com/sagefantasma/MGS2-Cheat-Trainer/assets/8712389/f639e114-733c-4b53-b0dd-dc786cc5af0e)

**Comment by sagefantasma** [comment]
Going to close this bug as fixed. I believe it should've been fixed in 1.2.0 and I haven't seen hide nor tail of this issue since then.
